Back end v1.1
TUD-KInD/periscope-public-engagement-tool pull request #7
Opened 2021-04-28 16:47 UTC by vincentgong7

Please review the code for Task 1.

2021-04-28 20:32 UTC, yenchiah commented on back-end/www/app.py
> +from controllers import root, other_controller
Why this line is here? Please put the code for importing modules together (for example, move it to line 6).

2021-04-28 20:37 UTC, yenchiah commented on back-end/www/app.py
> +app.register_blueprint(root.bp)
Please provide comments about what this line is doing

2021-04-28 20:39 UTC, yenchiah commented on back-end/www/app.py
> +app.register_blueprint(other_controller.bp, url_prefix='/other_controller')
Please provide comments about what this line is doing.

2021-04-28 20:50 UTC, yenchiah commented on back-end/www/controllers/__init__.py
> +    f)[:-3] for f in glob.glob(os.path.dirname(__file__) + "/*.py")]
Please do only one line for this code (no need for two lines). In general, we will only break a line into two lines if it is longer than 99 characters.

2021-04-28 20:53 UTC, yenchiah commented on back-end/www/controllers/__init__.py
> +    f)[:-3] for f in glob.glob(os.path.dirname(__file__) + "/*.py")]
Please put one blank line between the "__all__ = ..." and the imports.

2021-04-28 20:55 UTC, yenchiah commented on back-end/www/app.py
> +app.register_blueprint(root.bp)
Please provide comments about what this line is doing.

2021-04-28 20:56 UTC, yenchiah commented on back-end/www/controllers/__init__.py
> +    f)[:-3] for f in glob.glob(os.path.dirname(__file__) + "/*.py")]
Please provide comments about what this line is doing.

2021-04-28 21:02 UTC, yenchiah commented on back-end/www/controllers/other_controller.py
> +from werkzeug.security import check_password_hash, generate_password_hash
Why do we need this import? Please remove this line if the modules are not used.

2021-04-28 21:05 UTC, yenchiah commented on back-end/www/controllers/__init__.py
> +import glob
test

2021-04-28 21:09 UTC, yenchiah commented on back-end/www/app.py
On line 4, remove the User class from the import since we are not using it anymore.

2021-04-28 21:12 UTC, yenchiah commented on back-end/www/controllers/other_controller.py
> +	return 'other_controller/test'
The indentation looks wrong. It should be 4 spaces. Please fix it.

2021-04-28 21:14 UTC, yenchiah commented on back-end/www/controllers/other_controller.py
> +)
It looks like only the Blueprint module is used. Please remove the modules that are not used.

2021-04-28 21:17 UTC, yenchiah commented on back-end/www/app.py
> +app.register_blueprint(other_controller.bp, url_prefix='/other_controller')
For line 14, please use double quote (let's use double quote in our project).

2021-04-28 21:18 UTC, yenchiah commented on back-end/www/controllers/other_controller.py
> +bp = Blueprint('other_controller', __name__)
For line 7, please use double quote (let's use double quote in our project).

2021-04-28 21:20 UTC, yenchiah commented on back-end/www/controllers/other_controller.py
> +	return 'other_controller/test'
From line 10, please follow the sub-task in the opened issue to move the hello_world() function that was in the app.py file here.

2021-04-28 21:24 UTC, yenchiah commented on back-end/www/controllers/root.py
> +	return 'root'
From line 11, please move the code in the hello_world() function that was in the app.py file here. In this way, we can test if the database query works.

2021-04-28 21:24 UTC, yenchiah commented on back-end/www/controllers/root.py
> +from werkzeug.security import check_password_hash, generate_password_hash
Please remove unused modules.

2021-04-28 21:25 UTC, yenchiah commented on back-end/www/controllers/root.py
> +from werkzeug.security import check_password_hash, generate_password_hash
Please remove unused modules from line 1 to line 5.

2021-04-28 21:25 UTC, yenchiah commented on back-end/www/controllers/root.py
> +from werkzeug.security import check_password_hash, generate_password_hash
Please remove unused modules from line 1 to line 5.

2021-04-28 21:25 UTC, yenchiah commented on back-end/www/controllers/root.py
> +	return 'root'
The indentation on line 12 looks wrong. It should be 4 spaces. Please fix it.

2021-04-28 21:27 UTC, yenchiah commented on back-end/www/controllers/other_controller.py
> +from werkzeug.security import check_password_hash, generate_password_hash
Please remove unused modules from line 1 to line 5.

2021-04-28 21:32 UTC, yenchiah commented on back-end/www/controllers/other_controller.py
> +	return 'other_controller/test'
Please check why "http://localhost:5000/test" is not working.

2021-04-28 21:33 UTC, yenchiah requested changes
Please address all the comments that I have. Thanks.

2021-04-29 14:04 UTC, vincentgong7 commented on back-end/www/app.py
> +from controllers import root, other_controller
Done.

2021-04-29 14:05 UTC, vincentgong7 commented on back-end/www/app.py
> +app.register_blueprint(other_controller.bp, url_prefix='/other_controller')
Done

2021-04-29 14:06 UTC, vincentgong7 commented on back-end/www/controllers/__init__.py
> +    f)[:-3] for f in glob.glob(os.path.dirname(__file__) + "/*.py")]
Done

2021-04-29 14:07 UTC, vincentgong7 commented on back-end/www/controllers/__init__.py
> +    f)[:-3] for f in glob.glob(os.path.dirname(__file__) + "/*.py")]
Done

2021-04-29 14:07 UTC, vincentgong7 commented on back-end/www/app.py
> +app.register_blueprint(root.bp)
Done

2021-04-29 14:10 UTC, vincentgong7 commented on back-end/www/controllers/__init__.py
> +    f)[:-3] for f in glob.glob(os.path.dirname(__file__) + "/*.py")]
Done.

2021-04-29 14:12 UTC, vincentgong7 commented on back-end/www/app.py
Done

2021-04-29 14:12 UTC, vincentgong7 commented on back-end/www/controllers/other_controller.py
> +	return 'other_controller/test'
Done

2021-04-29 14:14 UTC, vincentgong7 commented on back-end/www/app.py
> +app.register_blueprint(other_controller.bp, url_prefix='/other_controller')
Ok. Done.

2021-04-29 14:17 UTC, vincentgong7 commented on back-end/www/controllers/other_controller.py
> +bp = Blueprint('other_controller', __name__)
Done.

2021-04-29 14:23 UTC, vincentgong7 commented on back-end/www/controllers/root.py
> +	return 'root'
Done

2021-04-29 14:24 UTC, vincentgong7 commented on back-end/www/controllers/root.py
> +from werkzeug.security import check_password_hash, generate_password_hash
Done

2021-04-29 14:25 UTC, vincentgong7 commented on back-end/www/controllers/root.py
> +from werkzeug.security import check_password_hash, generate_password_hash
Done

2021-04-29 14:25 UTC, vincentgong7 commented on back-end/www/controllers/root.py
> +	return 'root'
Done

2021-04-29 14:28 UTC, vincentgong7 commented on back-end/www/controllers/other_controller.py
> +from werkzeug.security import check_password_hash, generate_password_hash
Done

2021-04-30 10:51 UTC, merged